'use strict';
const menu=document.querySelector('#mobile-menu');
const menuButton=document.querySelector('.menu-toggle');
const viewer=document.querySelector('#image-viewer');
const lock=()=>document.body.classList.toggle('modal-open',!!document.querySelector('dialog[open]'));
menuButton?.addEventListener('click',()=>{menu.showModal();menuButton.setAttribute('aria-expanded','true');lock()});
menu?.querySelector('.menu-close').addEventListener('click',()=>menu.close());
menu?.addEventListener('close',()=>{menuButton.setAttribute('aria-expanded','false');lock()});
menu?.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>menu.close()));
const filters=[...document.querySelectorAll('[data-filter]')];
filters.forEach(button=>button.addEventListener('click',()=>{const selected=button.dataset.filter;filters.forEach(b=>b.setAttribute('aria-pressed',String(b===button)));let count=0;document.querySelectorAll('.project-card').forEach(card=>{card.hidden=selected!=='all'&&card.dataset.category!==selected;if(!card.hidden)count++});document.querySelector('.project-grid').classList.toggle('is-filtered',selected!=='all');document.querySelector('#filter-status').textContent=`${count} ${count===1?'project':'projects'} shown`;}));
const galleries={courtyard:{title:'The Quiet Courtyard',images:[['assets/courtyard.png','01 / Courtyard — water, enclosure and the olive tree.'],['assets/interior.png','02 / Gallery study — oak, concrete and bronze.'],['assets/passage.png','03 / Threshold study — light across the mineral envelope.']]},'common-ground':{title:'Common Ground',images:[['assets/common-ground.png','Commercial interiors / 2025 — Concept preview.']]},house:{title:'House of Light',images:[['assets/house.png','Residential architecture / 2025 — Concept preview.']]}};
let active=null,index=0;
const render=()=>{const[image,caption]=active.images[index];const img=document.querySelector('#viewer-image');img.src=image;img.alt=caption;document.querySelector('#viewer-title').textContent=active.title;document.querySelector('#viewer-caption').textContent=caption;document.querySelector('#viewer-count').textContent=`${String(index+1).padStart(2,'0')} / ${String(active.images.length).padStart(2,'0')}`;const previous=viewer.querySelector('.viewer-prev'),next=viewer.querySelector('.viewer-next');previous.disabled=index===0;next.disabled=index===active.images.length-1;previous.hidden=next.hidden=active.images.length===1;};
document.querySelectorAll('[data-view]').forEach(link=>link.addEventListener('click',e=>{if(typeof viewer.showModal!=='function')return;e.preventDefault();active=galleries[link.dataset.view];index=Number(link.dataset.index||0);render();viewer.showModal();lock()}));
viewer?.querySelector('.viewer-close').addEventListener('click',()=>viewer.close());
viewer?.addEventListener('close',lock);
viewer?.querySelector('.viewer-prev').addEventListener('click',()=>{if(index>0){index--;render()}});
viewer?.querySelector('.viewer-next').addEventListener('click',()=>{if(index<active.images.length-1){index++;render()}});
viewer?.addEventListener('keydown',e=>{if(e.key==='ArrowRight'&&index<active.images.length-1){e.preventDefault();index++;render()}else if(e.key==='ArrowLeft'&&index>0){e.preventDefault();index--;render()}});
